export const FACTIONS = [
    {
        id: "survey-corps",
        name: "Scout Regiment",
        tagline: "Humanity's boldest",
        logo: "/logos/scouts.webp",
        accent: "border-green-800/60 hover:shadow-[0_0_45px_rgba(21,128,61,0.35)]",
        chipColor: "text-green-500",
        desc:
            "The military branch that ventures beyond the walls to fight Titans directly and reclaim humanity's lost territory. Its members bear the Wings of Freedom on their cloaks and pay the highest casualty rate of any regiment.",
        characters: [
            { name: "Eren Yeager", img: "/chars/eren.png", role: "Founding & Attack Titan holder", desc: "A cadet driven by an all-consuming hatred of Titans after witnessing his mother's death. He inherits the Founding Titan and becomes the architect of the Rumbling, before being killed by Mikasa at the war's end." },
            { name: "Mikasa Ackermann", img: "/chars/mikasa.png", role: "Ackerman clan, veteran soldier", desc: "The last known member of the Ackerman clan outside Kenny's line, adopted by the Yeager family after her parents' murder. She graduates at the top of her class and, after the war's end, finally finds a quieter life." },
            { name: "Armin Arlelt", img: "/chars/armin.jpg", role: "Colossal Titan holder", desc: "Eren and Mikasa's childhood friend, valued for his strategic mind rather than raw combat skill. He inherits the Colossal Titan from Bertholdt and later works as a diplomat trying to keep a fragile peace." },
            { name: "Erwin Smith", img: "/chars/erwin.png", role: "13th Commander of the Survey Corps", desc: "A brilliant and ruthless strategist willing to sacrifice his soldiers — and himself — for the truth about the world beyond the walls. His final charge against the Beast Titan cements his legacy." },
            { name: "Levi Ackermann", img: "/chars/levi.png", role: "Humanity's strongest soldier", desc: "A former Underground City thug recruited by Erwin Smith. His unmatched blade skill carries him through the war, though he survives it gravely wounded, into a quieter, harder-won peace." },
            { name: "Jean Kirschtein", img: "/chars/jean.png", role: "Squad leader", desc: "Initially set on joining the Military Police for an easy life, Jean grows into a dependable, level-headed leader who survives the final war and helps shape what comes after." },
            { name: "Conny Springer", img: "/characters/conny-springer.png", role: "Scout", desc: "A cheerful cadet from a Wall Rose village whose good humor masks a deep personal tragedy, who survives the war carrying the weight of what happened to his own hometown." },
            { name: "Sasha Braus", img: "/characters/sasha-braus.png", role: "Scout", desc: "Nicknamed \"Potato Girl,\" a skilled hunter with sharp instincts and a bottomless appetite. Her warmth carries the 104th's emotional core until she is fatally shot during the raid on Liberio." },
            { name: "Hange Zoë", img: "/chars/hange.png", role: "14th Commander of the Survey Corps", desc: "An eccentric Titan researcher whose scientific curiosity is matched only by their loyalty to their comrades. They succeed Erwin as commander and give their life holding the line against the Colossal Titan." },
            { name: "Ymir", img: "/characters/ymir.png", role: "104th cadet, Jaw Titan holder", desc: "A quiet, self-sacrificing cadet secretly a Titan shifter herself, who ultimately gives her life to save Historia and reveal the truth about her own curse." },
            { name: "Miche Zacharius", img: "/chars/miche.png", role: "Section commander", desc: "The Scouts' renowned second-in-command, famed for an almost supernatural sense of smell for Titans. He is ambushed and killed by the Beast Titan's coordinated horde at Wall Rose." },
            { name: "Moblit Berner", img: "/characters/moblit-berner.png", role: "Hange's aide", desc: "Hange's endlessly patient and long-suffering assistant, forever cleaning up after their commander's reckless research. He dies protecting his squad during the retreat from Shiganshina." },
            { name: "Nanaba", img: "/characters/nanaba.png", role: "Squad leader", desc: "A capable, level-headed veteran Scout entrusted with her own squad. She is killed defending her comrades from a Titan-transformed intruder deep in the forest." },
            { name: "Gelgar", img: "/characters/gelgar.png", role: "Scout", desc: "A cheerful, hard-drinking veteran soldier who falls alongside Nanaba's squad in the same forest ambush." },
            { name: "Henning", img: "/characters/henning.png", role: "Scout", desc: "A steady veteran Scout lost fighting the same Titan-transformed threat that claimed Nanaba's squad." },
            { name: "Lynne", img: "/characters/lynne.png", role: "Scout", desc: "A veteran female Scout killed in the same forest encounter that devastated her unit." },
            { name: "Oruo Bozad", img: "/characters/oruo-bozad.png", role: "Levi's squad", desc: "A member of Levi's elite squad who imitates his captain's mannerisms down to the last detail, killed by the Female Titan during her rampage toward Eren." },
            { name: "Petra Rall", img: "/characters/petra-rall.png", role: "Levi's squad", desc: "A skilled, kind-hearted soldier in Levi's Special Operations Squad, cut down alongside her comrades in the Female Titan's ambush." },
            { name: "Eld Gin", img: "/characters/eld-gin.png", role: "Levi's squad, second-in-command", desc: "The composed second-in-command of Levi's squad, killed defending it from the Female Titan's assault." },
            { name: "Gunther Schultz", img: "/characters/gunther-schultz.png", role: "Levi's squad", desc: "A dependable member of Levi's Special Operations Squad, lost in the same ambush that claimed the rest of his unit." },
            { name: "Furlan Church", img: "/characters/furlan-church.png", role: "Levi's Underground trio", desc: "A sharp, loyal member of Levi's old Underground City gang, killed by Titans during their very first mission as Scouts." },
            { name: "Isabel Magnolia", img: "/characters/isabel-magnolia.png", role: "Levi's Underground trio", desc: "The spirited youngest of Levi's Underground gang, who dies protecting her friends on that same doomed first expedition." },
            { name: "Ilse Langnar", img: "/characters/ilse-langnar.png", role: "Scout, scholar", desc: "A curious soldier who kept a journal theorizing about Titan intelligence, devoured on a solo expedition before she could share her findings." },
            { name: "Nifa", img: "/characters/nifa.png", role: "Levi Squad member", desc: "A sharp Scout attached to Levi's unit, killed while investigating the truth behind Historia's connection to the royal Reiss family." },
            { name: "Flagon", img: "/characters/flagon.png", role: "Scout", desc: "A Scout Regiment soldier killed defending Trost District during the initial Titan breach." },
            { name: "Marlo Freudenberg", img: "/characters/marlo-freudenberg.png", role: "Scout hopeful", desc: "An idealistic soldier whose search for justice within a corrupt system leads him toward the Scouts, a path that costs him his life." },
            { name: "Moses", img: "/characters/moses.png", role: "Scout", desc: "A Scout Regiment soldier lost during one of the countless costly expeditions beyond the walls." },
            { name: "Tomas", img: "/characters/tomas.png", role: "Scout", desc: "A young soldier who traded a cadet's uniform for a Scout's cloak, killed in action shortly after." },
            { name: "Dieter", img: "/characters/dieter.png", role: "Scout", desc: "A Scout Regiment soldier who perished during an expedition beyond Wall Rose." },
            { name: "Dirk", img: "/characters/dirk.png", role: "Scout", desc: "Another rank-and-file casualty among the many Scouts who never returned from the field." },
            { name: "Marlene", img: "/characters/marlene.png", role: "Scout", desc: "A Scout Regiment soldier who gave her life for humanity's cause on an expedition beyond the walls." },
            { name: "Klaus", img: "/characters/klaus.png", role: "Scout", desc: "A soldier of the Scout Regiment who fell in battle against the Titans." },
            { name: "Harold", img: "/characters/harold.png", role: "Scout", desc: "A member of the Scout Regiment lost during one of Erwin's costly campaigns beyond the walls." },
            { name: "Keiji", img: "/characters/keiji.png", role: "Scout", desc: "A Scout Regiment soldier who died on an expedition beyond the walls." },
            { name: "Abel", img: "/characters/abel.png", role: "Scout", desc: "A member of the Scout Regiment's rank and file, lost to the Titans in the field." },
            { name: "Rashad", img: "/characters/rashad.png", role: "Scout", desc: "A Scout who perished during combat operations beyond the walls." },
            { name: "Lauda", img: "/characters/lauda.png", role: "Scout", desc: "A Scout Regiment member lost in the line of duty." },
            { name: "Peer", img: "/characters/peer.png", role: "Scout", desc: "Another fallen soldier among the Scout Regiment's many casualties." },
            { name: "Beirer", img: "/characters/beirer.png", role: "Scout", desc: "A Scout Regiment soldier who died beyond the walls in service of the expedition." },
            { name: "Jurgen", img: "/characters/jurgen.png", role: "Scout", desc: "A Scout Regiment soldier killed in combat during an expedition." },
            { name: "Ivan", img: "/characters/ivan.png", role: "Scout", desc: "A member of the Scout Regiment's rank and file, lost fighting the Titans." },
            { name: "Charrette", img: "/characters/charrette.png", role: "Scout", desc: "A Scout Regiment soldier who fell in the field during a mission beyond the walls." },
            { name: "Dieter Ness", img: "/characters/dieter-ness.png", role: "Scout", desc: "A Scout Regiment soldier lost during an expedition beyond the walls." },
            { name: "Luke Cis", img: "/characters/luke-cis.png", role: "Scout", desc: "A member of the Scout Regiment killed in action on an expedition." },
            { name: "Buchwald", img: "/characters/buchwald.png", role: "Scout", desc: "A member of the Scout Regiment's rank and file, one of the many soldiers who keep the formation moving beyond the walls." },
            { name: "Sandra", img: "/characters/sandra.png", role: "Scout", desc: "A Scout Regiment soldier lost during a mission beyond the walls." },
            { name: "Gordon", img: "/characters/gordon.png", role: "Scout", desc: "A fellow Scout who died in the line of duty as part of Erwin's dwindling ranks." },
            { name: "Varis", img: "/characters/varis.png", role: "Scout (Pure Titan)", desc: "A Scout Regiment member who ultimately becomes one of the mindless Titans that plague humanity, his identity lost to Ymir's curse." },
        ],
    },
    {
        id: "military-police",
        name: "Military Police Regiment",
        tagline: "Order behind Wall Sina",
        logo: "/logos/mp.webp",
        accent: "border-stone-400/40 hover:shadow-[0_0_45px_rgba(168,162,158,0.3)]",
        chipColor: "text-stone-300",
        desc:
            "Reserved for the top graduates of each training class, the Military Police serve the king directly from the safety of the interior, maintaining order — and, often, corruption — within Wall Sina.",
        characters: [
            { name: "Nile Dawk", img: "/characters/nile-dawk.png", role: "Commander of the Military Police (Titan)", desc: "The MP's top commander, caught between loyalty to the crown and the political games of the interior. His authority collapses along with his fate once the truth about the royal family comes to light." },
            { name: "Kenny Ackermann", img: "/chars/kenny.png", role: "Captain, Anti-Personnel Squad", desc: "Levi's uncle and a member of the Ackerman bloodline, once an Underground City killer turned royal enforcer. His brutal efficiency and tragic backstory reveal much about his clan's true nature." },
            { name: "Waltz", img: "/characters/waltz.png", role: "MP officer", desc: "A Military Police officer stationed within the interior, insulated from the direct threat the Scouts face beyond the walls." },
            { name: "Boris Feulner", img: "/characters/boris-feulner.png", role: "MP officer", desc: "An officer serving under the Military Police's command structure inside Wall Sina." },
            { name: "Dennis Aiblinger", img: "/characters/dennis-aiblinger.png", role: "MP officer", desc: "A Military Police officer assigned to administrative duties within the walls." },
            { name: "Roger", img: "/characters/roger.png", role: "MP soldier", desc: "A Military Police soldier drawn into the political intrigue surrounding the royal government." },
            { name: "Roeg", img: "/characters/roeg.png", role: "MP officer (Titan)", desc: "A Military Police officer whose story ends in transformation into a mindless Titan." },
            { name: "Traute Carven", img: "/characters/traute-carven.png", role: "MP officer", desc: "A Military Police officer who died amid the chaos surrounding the royal family's hidden secrets." },
            { name: "Duran", img: "/characters/duran.png", role: "MP soldier", desc: "A minor Military Police figure whose brief appearance in the story ends in death." },
        ],
    },
    {
        id: "garrison",
        name: "Garrison Regiment",
        tagline: "Guardians of the walls",
        logo: "/logos/garrison.webp",
        accent: "border-blue-800/60 hover:shadow-[0_0_45px_rgba(30,64,175,0.35)]",
        chipColor: "text-blue-400",
        desc:
            "Stationed along the walls themselves, the Garrison maintains the defenses, mans the cannons, and holds the line whenever a breach occurs — the first line of response inside the walls.",
        characters: [
            { name: "Dot Pyxis", img: "/characters/dot-pyxis.png", role: "Commander, southern territories", desc: "A veteran commander known for his unorthodox tactics and constant drinking. His decisive gambit at Trost — collapsing the district's gate district — helps humanity survive the assault." },
            { name: "Hannes", img: "/characters/hannes.png", role: "Garrison soldier", desc: "A family friend of the Yeager household who fails to save Eren's mother from a Titan, a failure he tries — and ultimately dies trying — to atone for years later." },
            { name: "Ian Dietrich", img: "/characters/ian-dietrich.png", role: "Garrison squad leader", desc: "A hardened Garrison soldier who leads reinforcements into the ruins of Trost, giving his life to help evacuate civilians during the district's darkest hour." },
            { name: "Mitabi Jarnach", img: "/characters/mitabi-jarnach.png", role: "Garrison squad leader", desc: "A squad leader who commands the desperate defense of Trost's interior before falling to the Titans himself." },
            { name: "Kitz Woermann", img: "/characters/kitz-woermann.png", role: "Garrison commander", desc: "The stern commander who oversees cadet graduation and Garrison operations at Wall Rose." },
            { name: "Gustav", img: "/characters/gustav.png", role: "Garrison instructor", desc: "A Garrison soldier who trains new recruits in wall maintenance and defense procedures." },
            { name: "Carsten", img: "/characters/carsten.png", role: "Garrison soldier", desc: "A Garrison soldier stationed to maintain the walls' cannon emplacements." },
            { name: "Anka Rheinberger", img: "/characters/anka-rheinberger.png", role: "Garrison soldier", desc: "A Garrison soldier and former classmate of Annie Leonhart, killed in the line of duty." },
            { name: "Hugo", img: "/characters/hugo.png", role: "Garrison soldier", desc: "A Garrison Regiment soldier lost defending the walls." },
            { name: "Phil", img: "/characters/phil.png", role: "Garrison soldier ?", desc: "A member of the Garrison Regiment whose ultimate fate remains unclear." },
        ],
    },
    {
        id: "cadet-corps",
        name: "Cadet Corps",
        tagline: "The 104th and beyond",
        logo: "/logos/training.webp",
        accent: "border-amber-700/50 hover:shadow-[0_0_45px_rgba(180,83,9,0.3)]",
        chipColor: "text-amber-500",
        desc:
            "Every soldier begins here: three brutal years of training under the Cadet Corps, learning the Vertical Maneuvering Equipment and hand-to-hand combat before choosing which regiment to serve.",
        characters: [
            { name: "Keith Sadies", img: "/characters/keith-sadies.png", role: "104th drill instructor", desc: "The gruff, demanding drill instructor of the 104th Training Corps, whose harsh methods forged the cadets who would go on to fight for humanity's survival." },
            { name: "Marco Bodt", img: "/characters/marco-bodt.png", role: "104th cadet", desc: "A dutiful, well-liked cadet who dreamed of joining the Military Police, killed under mysterious circumstances during the Battle of Trost." },
            { name: "Mina Carolina", img: "/characters/mina-carolina.png", role: "104th cadet", desc: "A cadet who befriended Sasha during training, devoured shortly after graduation during the fall of Trost District." },
            { name: "Franz Kefka", img: "/characters/franz-kefka.png", role: "104th cadet", desc: "Hanna's devoted cadet boyfriend, killed defending Trost District during the Titans' first breach." },
            { name: "Hanna Diament", img: "/characters/hanna-diament.png", role: "104th cadet", desc: "A cadet who trained alongside Franz, her closest companion, before the horrors of the Battle of Trost." },
            { name: "Thomas Wagner", img: "/characters/thomas-wagner.png", role: "104th cadet", desc: "A cadet killed during the desperate defense of Trost District." },
            { name: "Nack Tierce", img: "/characters/nack-tierce.png", role: "104th cadet", desc: "A cynical cadet obsessed with joining the Military Police for an easy life, killed while fleeing the Titans at Trost." },
            { name: "Tom", img: "/characters/tom.png", role: "Cadet", desc: "A cadet killed in the opening days of the Titan invasion of Trost." },
            { name: "Milieus Zeremski", img: "/characters/milieus-zeremski.png", role: "Cadet", desc: "A cadet lost amid the chaos of the Battle of Trost." },
            { name: "Ruth D. Kline", img: "/characters/ruth-d-kline.png", role: "Cadet", desc: "A minor cadet lost during the Titans' breach of Trost District." },
        ],
    },
    {
        id: "marleyan-military",
        name: "Marleyan Military",
        tagline: "The mainland's iron fist",
        logo: "/logos/marley.jpg",
        accent: "border-red-800/60 hover:shadow-[0_0_45px_rgba(153,27,27,0.4)]",
        chipColor: "text-red-500",
        desc:
            "The regular armed forces of Marley, the dominant power across the sea, which oversees the Warrior program and enforces the empire's rule over its Eldian subjects.",
        characters: [
            { name: "Theo Magath", img: "/characters/theo-magath.png", role: "Marley General", desc: "A pragmatic, battle-hardened commander overseeing the Warrior program, who grows disillusioned with Marley's leadership as the true cost of its wars becomes clear." },
            { name: "Müller", img: "/characters/muller.png", role: "Marleyan officer", desc: "A Marleyan officer overseeing part of the Warrior program's rigorous training regimen." },
            { name: "Koslow", img: "/characters/koslow.png", role: "Marleyan soldier", desc: "A Marleyan soldier killed during Eren's assault on the internment zone of Liberio." },
            { name: "Carlo", img: "/characters/carlo.png", role: "Marleyan officer", desc: "A Marleyan military officer lost in the fighting against Eren's forces." },
            { name: "Calvi", img: "/characters/calvi.png", role: "Marleyan soldier", desc: "A member of Marley's military killed in action during the war's final chapters." },
        ],
    },
    {
        id: "warriors",
        name: "Warriors",
        tagline: "Eldian children, Marleyan weapons",
        logo: "/logos/marley.jpg",
        accent: "border-orange-700/50 hover:shadow-[0_0_45px_rgba(194,65,12,0.35)]",
        chipColor: "text-orange-400",
        desc:
            "Eldian children raised from birth by Marley to inherit one of the Nine Titans, trained to fight and die for an empire that treats their own people as subhuman.",
        characters: [
            { name: "Zeke Yeager", img: "/chars/zeke.png", role: "Beast Titan holder", desc: "Eren's half-brother and Grisha's estranged son, raised in Marley to become its most celebrated Warrior. He is killed protecting Armin during the final battle against the Rumbling." },
            { name: "Reiner Braun", img: "/chars/reiner.png", role: "Armored Titan holder", desc: "A Warrior candidate who infiltrated Paradis under a false identity for years, orchestrating the fall of Wall Maria. Haunted by guilt, he survives the war and tries to build a life with it." },
            { name: "Annie Leonhart", img: "/chars/annie.png", role: "Female Titan holder", desc: "A Warrior trained by her father to survive at any cost, sent to Paradis to capture Eren. She spends years encased in crystal before emerging into a changed world." },
            { name: "Pieck Finger", img: "/characters/pieck-finger.png", role: "Cart Titan holder", desc: "A calm, analytical Warrior whose Titan form favors speed and mobility over brute strength, frequently used for reconnaissance and rapid transport of heavy weaponry." },
            { name: "Falco Grice", img: "/characters/falco-grice.png", role: "Warrior candidate, later Jaw Titan holder", desc: "A gentle, self-doubting candidate devoted to Gabi's safety, later transformed unexpectedly into a Titan bearing echoes of Zeke's own power." },
            { name: "Gabi Braun", img: "/characters/gabi-braun.png", role: "Warrior candidate", desc: "Reiner's young cousin and a top Warrior candidate, raised to see Eldians on Paradis as devils. Her worldview is violently shattered over the course of the final war." },
            { name: "Marcel Galliard", img: "/characters/marcel-galliard.png", role: "Original Jaw Titan holder", desc: "Porco's kind elder brother, devoured by a Titan while trying to save Reiner and Bertholdt during their infiltration mission on Paradis." },
            { name: "Tom Xaver", img: "/characters/tom-xaver.png", role: "Original Armored Titan holder", desc: "The Warrior who held the Armored Titan before Reiner, dying of illness shortly after passing on his power." },
            { name: "Bertholdt Hoover", img: "/characters/bertholdt-hoover.png", role: "Colossal Titan holder", desc: "Reiner's quiet, anxious partner during the Paradis infiltration mission, responsible for the very first breach of Wall Maria. He is ultimately cut down after his Titan form is defeated in Shiganshina." },
            { name: "Porco Galliard", img: "/characters/porco-galliard.png", role: "Jaw Titan holder", desc: "A sharp-tongued Warrior and Marcel's younger brother, fiercely protective of Marley's interests, killed during Eren's final assault on Liberio." },
            { name: "Colt Grice", img: "/characters/colt-grice.png", role: "Warrior candidate", desc: "Falco's steady older brother and Porco's closest partner among the Warrior candidates, killed during Eren's raid on Liberio." },
            { name: "Udo", img: "/characters/udo.png", role: "Warrior candidate", desc: "A young Warrior candidate killed during Eren's assault on the Liberio internment zone." },
            { name: "Zofia", img: "/characters/zofia.png", role: "Warrior candidate", desc: "A Warrior candidate lost during the same devastating attack on Liberio." },
        ],
    },
    {
        id: "marley-security",
        name: "Marley Public Security & High Command",
        tagline: "Watching the watched",
        logo: "/logos/marley.jpg",
        accent: "border-zinc-500/40 hover:shadow-[0_0_45px_rgba(113,113,122,0.3)]",
        chipColor: "text-zinc-300",
        desc:
            "The internal forces that police Marley's Eldian population and the high command that quietly shapes the empire's use of its Titan weapons.",
        characters: [
            { name: "Eren Kruger", img: "/characters/eren-kruger.png", role: "Public Security officer, former Attack Titan holder", desc: "A secret Eldian agent embedded within Marley's public security forces and the previous Attack Titan holder, who passed his power — and his mission — on to Grisha Yeager." },
            { name: "Gross", img: "/characters/gross.png", role: "Public Security officer", desc: "A Marley Public Security officer killed in the line of duty." },
            { name: "Dhalis Zachary", img: "/characters/dhalis-zachary.png", role: "High-ranking military official", desc: "A high-ranking Marleyan official involved in overseeing the empire's policy toward its Eldian subjects and the Warrior program." },
        ],
    },
    {
        id: "house-reiss",
        name: "Nobility — House Reiss",
        tagline: "The bloodline of the Founder",
        logo: "/logos/sina.webp",
        accent: "border-yellow-600/50 hover:shadow-[0_0_45px_rgba(202,138,4,0.35)]",
        chipColor: "text-yellow-400",
        desc:
            "The royal family descended from King Karl Fritz, holders of the Founding Titan and architects of the century-long deception that kept Paradis isolated behind its walls.",
        characters: [
            { name: "Karl Fritz", img: "/characters/karl-fritz.png", role: "145th King of the Walls", desc: "The Founding Titan holder who abandoned Marley, sailed to Paradis, and swore the Oath of Pacifism — erasing his people's memories and forbidding them from ever fighting again." },
            { name: "Uri Reiss", img: "/characters/uri-reiss.png", role: "144th King, Founding Titan holder", desc: "A gentle, self-sacrificing king who preceded Frieda as Founding Titan holder, refusing to ever turn his power against his own people." },
            { name: "Rod Reiss", img: "/characters/rod-reiss.png", role: "Head of House Reiss", desc: "The true head of the royal bloodline, obsessed with reclaiming the Founding Titan's power at any cost, ultimately transforming into a mindless, colossal Titan of his own." },
            { name: "Frieda Reiss", img: "/characters/frieda-reiss.png", role: "Former Founding Titan holder", desc: "Rod's eldest daughter and the Founding Titan's holder before Eren, killed and devoured by Grisha Yeager in order to pass the power to his son." },
            { name: "Historia Reiss", img: "/chars/historia.png", role: "Cadet, later Queen of the Walls", desc: "Born Krista Lenz, an illegitimate member of the royal Reiss bloodline. After training with the 104th, she reclaims her true identity and ascends to the throne to reshape the kingdom." },
            { name: "Rod and Uri's father", img: "/characters/reiss-patriarch.png", role: "Head of House Reiss", desc: "The patriarch of House Reiss in the generation before Rod and Uri, who passed down the Founding Titan's heavy burden to his sons." },
            { name: "Frieda's mother", img: "/characters/friedas-mother.png", role: "Reiss household", desc: "Rod Reiss's wife and Frieda's mother, a quiet figure within the isolated royal household." },
            { name: "Florian Reiss", img: "/characters/florian-reiss.png", role: "House Reiss ancestor", desc: "A figure from the Reiss family's long lineage, tied to the family's secret guardianship of the Founding Titan." },
            { name: "Abel Reiss", img: "/characters/abel-reiss.png", role: "House Reiss ancestor", desc: "Another figure from an earlier generation of the Reiss bloodline." },
            { name: "Dirk Reiss", img: "/characters/dirk-reiss.png", role: "Former head of House Reiss", desc: "A past head of House Reiss during an earlier chapter of the family's long, hidden history." },
            { name: "Ulklin Reiss", img: "/characters/ulklin-reiss.png", role: "House Reiss ancestor", desc: "A member of the Reiss bloodline from an earlier generation of the royal family's history." },
            { name: "Wald", img: "/characters/wald-reiss.png", role: "Reiss household retainer", desc: "A retainer connected to the royal Reiss household's inner circle on Paradis." },
            { name: "Nicholas Lovof", img: "/characters/nicholas-lovof.png", role: "Royal courtier", desc: "A courtier tied to the royal government's inner circle within Wall Sina." },
        ],
    },
    {
        id: "tybur",
        name: "Nobility — The Tybur Family",
        tagline: "Keepers of the War Hammer",
        logo: "/logos/tybur.jpg",
        accent: "border-purple-800/50 hover:shadow-[0_0_45px_rgba(107,33,168,0.35)]",
        chipColor: "text-purple-400",
        desc:
            "A powerful Eldian noble family permitted to remain in Marley's mainland due to their long-standing role as its diplomats — and their secret guardianship of the War Hammer Titan.",
        characters: [
            { name: "Willy Tybur", img: "/characters/willy-tybur.png", role: "War Hammer Titan holder", desc: "Heir to the Tybur family fortune, who publicly reveals the truth of the Attack Titan's history at Liberio's founding-day festival — moments before his own fatal transformation." },
            { name: "Lara Tybur", img: "/characters/lara-tybur.png", role: "War Hammer Titan holder", desc: "Willy's younger sister, who inherits the War Hammer Titan after his death and later joins the alliance of nations assembled to stop Eren's Rumbling." },
            { name: "Fine Tybur", img: "/characters/fine-tybur.png", role: "Tybur family ?", desc: "A member of the Tybur family, Marley's Eldian diplomats and the secret guardians of the War Hammer Titan's bloodline." },
            { name: "Alois Tybur", img: "/characters/alois-tybur.png", role: "Tybur family", desc: "A minor figure within the extended Tybur family lineage." },
            { name: "Bruno Tybur", img: "/characters/bruno-tybur.png", role: "Tybur family", desc: "A member of the Tybur family tree, tied to their long diplomatic legacy in Marley." },
            { name: "Rico Tybur", img: "/characters/rico-tybur.png", role: "Tybur family", desc: "A lesser-known relative within the Tybur household." },
        ],
    },
    {
        id: "eldia",
        name: "Legendary Eldia — The Fritz Line",
        tagline: "Two thousand years of history",
        logo: "/logos/eldya.png",
        accent: "border-amber-500/50 hover:shadow-[0_0_45px_rgba(217,119,6,0.35)]",
        chipColor: "text-amber-300",
        desc:
            "The legendary founders of the Eldian Empire and the Titan power itself — figures from two thousand years past whose choices still shape the walls, the war, and everyone in it.",
        characters: [
            { name: "Ymir Fritz", img: "/characters/ymir-fritz.png", role: "The first Titan", desc: "The original source of all nine Titan powers, an enslaved girl whose fate two thousand years ago set the entire tragedy of the Eldian and Marleyan peoples into motion." },
            { name: "Fritz", img: "/characters/fritz-founder.png", role: "First King of Eldia", desc: "The legendary king who first inherited the Founding Titan from Ymir and began the Eldian royal bloodline that rules to this day." },
            { name: "Maria Fritz", img: "/characters/maria-fritz.png", role: "Daughter of King Fritz", desc: "One of King Fritz's daughters, for whom the great outer Wall Maria is named." },
            { name: "Rose Fritz", img: "/characters/rose-fritz.png", role: "Daughter of King Fritz", desc: "Another of King Fritz's daughters, similarly commemorated in the naming of the second great wall, Rose." },
            { name: "Sina Fritz", img: "/characters/sina-fritz.png", role: "Daughter of King Fritz", desc: "The third of King Fritz's daughters, for whom the innermost Wall Sina is named." },
        ],
    },
    {
        id: "civilians-paradis",
        name: "Civilians — Paradis Island",
        tagline: "Lives lived behind the walls",
        logo: "/logos/eldya.png",
        accent: "border-teal-700/50 hover:shadow-[0_0_45px_rgba(15,118,110,0.3)]",
        chipColor: "text-teal-400",
        desc:
            "The ordinary people of Paradis Island — families, merchants, priests, and children — whose lives are shaped and often shattered by the war being fought over their heads.",
        characters: [
            { name: "Grisha Yeager", img: "/chars/grisha.png", role: "Doctor, former Attack Titan holder", desc: "A former Marleyan Warrior candidate turned Paradis doctor and Eren's father, secretly the previous Attack Titan holder who orchestrated Frieda Reiss's death to steal the Founding Titan." },
            { name: "Carla Yeager", img: "/chars/carla.png", role: "Eren's mother", desc: "Eren's devoted mother, devoured by a Titan during the fall of Wall Maria — an act that sets her son on his path of vengeance." },
            { name: "Kuchel Ackermann", img: "/characters/kuchel-ackermann.png", role: "Levi's mother", desc: "Levi's mother, an Underground City sex worker who raised her son alone before her early death from illness." },
            { name: "Mikasa's mother", img: "/characters/mikasas-mother.png", role: "Ackerman family", desc: "Mikasa's mother, murdered by human traffickers when Mikasa was still a child." },
            { name: "Mikasa's father", img: "/characters/mikasas-father.png", role: "Ackerman family", desc: "Mikasa's father, killed in the same attack on their family that claimed his wife." },
            { name: "Armin's grandfather", img: "/characters/armins-grandfather.png", role: "Paradis civilian", desc: "Armin's grandfather, who raised him on forbidden stories of the world beyond the walls before perishing when Wall Maria fell." },
            { name: "Artur Braus", img: "/characters/artur-braus.png", role: "Sasha's father", desc: "Sasha's father, a hunter from her home village in the mountains beyond Wall Rose." },
            { name: "Lisa Braus", img: "/characters/lisa-braus.png", role: "Sasha's mother", desc: "Sasha's mother, living quietly in their mountain village while her daughter serves in the Scout Regiment." },
            { name: "Kaya", img: "/characters/kaya.png", role: "Ragako villager", desc: "A young girl from Ragako village whose life was saved by Sasha years before the story's main events." },
            { name: "Conny's mother", img: "/characters/connys-mother.png", role: "Springer family", desc: "Connie Springer's mother, later discovered transformed into a mindless Titan in their abandoned home village." },
            { name: "Conny's father", img: "/characters/connys-father.png", role: "Springer family (Titan)", desc: "Connie Springer's father, tragically found transformed into a mindless Titan roaming the ruins of his home village." },
            { name: "Sunny Springer", img: "/characters/sunny-springer.png", role: "Springer family", desc: "A member of Connie's family lost to the same tragedy that befell their village." },
            { name: "Martin Springer", img: "/characters/martin-springer.png", role: "Springer family", desc: "Another relative of Connie's, caught in the same village disaster." },
            { name: "Dimo Reeves", img: "/characters/dimo-reeves.png", role: "Trost merchant", desc: "A wealthy merchant of Trost District who dies trying to protect civilians as the Titans breach the wall." },
            { name: "Flegel Reeves", img: "/characters/flegel-reeves.png", role: "Trost merchant's son", desc: "Dimo Reeves's arrogant, spoiled son, more concerned with status than the looming Titan threat." },
            { name: "Nick", img: "/characters/nick-priest.png", role: "Order of the Walls priest", desc: "A priest secretly aware of the truth behind the walls, silenced by Kenny Ackerman's squad before he could reveal too much." },
            { name: "Kiyomi Azumabito", img: "/characters/kiyomi-azumabito.png", role: "Head of the Azumabito family", desc: "The head of the influential Azumabito family, an ally from the East who provides Paradis with vital resources, technology, and support." },
            { name: "Nicolo", img: "/characters/nicolo.png", role: "Former Marleyan soldier, cook", desc: "A former Marleyan soldier turned cook who joins Eren and Historia's circle after the war, choosing to serve rather than fight." },
            { name: "Fritz", img: "/characters/civilian-king-fritz.png", role: "Public decoy king", desc: "The public face of the monarchy presented to the people of Paradis, concealing the true royal bloodline's identity for generations." },
            { name: "Bandits", img: "/characters/bandits.png", role: "Underground City criminals", desc: "Unnamed criminals killed by a young Levi, Furlan, and Isabel during their days in the Underground City." },
            { name: "Kenny's grandpa", img: "/characters/kennys-grandpa.png", role: "Ackerman ancestor", desc: "An ancestor of Kenny Ackerman's line, tied to the family's long history in the Underground City." },
            { name: "Mr. Smith", img: "/characters/mr-smith.png", role: "Erwin's family", desc: "A figure connected to Erwin Smith's family, caught up in the fallout of his father's forbidden research into the world outside the walls." },
            { name: "Alma", img: "/characters/alma.png", role: "Paradis civilian", desc: "A civilian casualty of the long war fought over Paradis Island." },
            { name: "Kemper Boltz", img: "/characters/kemper-boltz.png", role: "Paradis civilian", desc: "A resident of Paradis killed amid one of the story's many calamities." },
            { name: "Moses' mother", img: "/characters/moses-mother.png", role: "Paradis civilian ?", desc: "The mother of a minor Scout Regiment soldier, her own fate left uncertain." },
            { name: "Marie Dawk", img: "/characters/marie-dawk.png", role: "Dawk family", desc: "A relative connected to the Dawk family within Paradis society." },
            { name: "Roderich", img: "/characters/roderich.png", role: "Paradis civilian", desc: "A resident of Paradis Island encountered within the walls." },
            { name: "Jean's mother", img: "/characters/jeans-mother.png", role: "Kirstein family", desc: "Jean Kirstein's mother, worried for her son's safety after his enlistment in the military." },
            { name: "Stohess District Mayor", img: "/characters/stohess-mayor.png", role: "Local official", desc: "The local official overseeing Stohess District at the time of the Female Titan incident." },
            { name: "Petra's father", img: "/characters/petras-father.png", role: "Rall family", desc: "Petra Rall's grieving father, left to mourn his daughter's death in the line of duty." },
            { name: "Ellie", img: "/characters/ellie.png", role: "Paradis civilian", desc: "A resident of Paradis Island going about ordinary life in the shadow of the walls." },
            { name: "Carly Stratmann", img: "/characters/carly-stratmann.png", role: "Paradis civilian", desc: "A civilian resident of Paradis Island's interior society." },
            { name: "Elliot G. Stratmann", img: "/characters/elliot-stratmann.png", role: "Paradis civilian", desc: "A member of the Stratmann family living on Paradis Island." },
            { name: "Lou", img: "/characters/lou.png", role: "Paradis civilian", desc: "A resident encountered within Paradis Island's walled society." },
            { name: "Ralph", img: "/characters/ralph.png", role: "Paradis civilian", desc: "Another ordinary inhabitant of the walls." },
            { name: "Djel Sannes", img: "/characters/djel-sannes.png", role: "Paradis civilian", desc: "A civilian figure connected to Paradis Island's interior population." },
            { name: "Aurille", img: "/characters/aurille.png", role: "Paradis civilian", desc: "A resident of Paradis Island living within the walls." },
            { name: "Gerald", img: "/characters/gerald.png", role: "Paradis civilian", desc: "Another ordinary inhabitant of Paradis Island." },
            { name: "Deltoff", img: "/characters/deltoff.png", role: "Paradis civilian", desc: "A civilian resident of Paradis Island." },
            { name: "Roy", img: "/characters/roy.png", role: "Paradis civilian", desc: "A resident within the walls of Paradis." },
            { name: "Peaure", img: "/characters/peaure.png", role: "Paradis civilian", desc: "A minor civilian figure within Paradis Island's population." },
            { name: "Yan", img: "/characters/yan.png", role: "Paradis civilian ?", desc: "A civilian whose ultimate fate is left unknown." },
            { name: "Wald", img: "/characters/wald-civilian.png", role: "Paradis civilian", desc: "A civilian of Paradis Island lost amid the story's turmoil." },
        ],
    },
    {
        id: "civilians-marley",
        name: "Civilians — Marley & Beyond",
        tagline: "After the uniforms come off",
        logo: "/logos/marley.jpg",
        accent: "border-rose-800/50 hover:shadow-[0_0_45px_rgba(159,18,57,0.3)]",
        chipColor: "text-rose-400",
        desc:
            "Former soldiers, Warriors, and ordinary Eldians living under Marley's rule — some trying to survive its discrimination, others trying to leave the war behind entirely.",
        characters: [
            { name: "Karina Braun", img: "/characters/karina-braun.png", role: "Reiner's mother", desc: "Reiner's mother, an Eldian woman in Marley who endures discrimination for her son's sake and waits anxiously for his return." },
            { name: "Yelena", img: "/characters/yelena.png", role: "Anti-Marleyan Volunteer, Zeke loyalist", desc: "A fervent believer in Zeke Yeager's plan, a former Marleyan soldier who allies with Eren and the Yeagerists to see her leader's vision through." },
            { name: "Onyankopon", img: "/characters/onyankopon.png", role: "Allied soldier, airship pilot", desc: "An Eldian ally from an allied African nation, notable for piloting Paradis's newly acquired airships in the war's final stretch." },
            { name: "Dina Fritz", img: "/characters/dina-fritz.png", role: "Eren's aunt (Titan)", desc: "Eren's biological aunt and Zeke's mother, transformed into a mindless Titan who devours Carla Yeager during the fall of Wall Maria." },
            { name: "Grisha's mother", img: "/characters/grishas-mother.png", role: "Yeager family", desc: "Grisha Yeager's mother, killed during the Eldian ghetto raids in Marley before her son's childhood escape." },
            { name: "Ramzi", img: "/characters/ramzi.png", role: "Grisha's childhood friend", desc: "A childhood friend of young Grisha in the Liberio ghetto, executed alongside his family for a supposed act of rebellion." },
            { name: "Halil", img: "/characters/halil.png", role: "Ramzi's father", desc: "Ramzi's father, executed with his family in the same tragedy that scarred Grisha's youth." },
            { name: "Yeager", img: "/characters/Yeager-family.png", role: "Yeager family", desc: "A member of the extended Yeager family line living under Marleyan rule." },
            { name: "Fay Yeager", img: "/characters/fay-Yeager.png", role: "Yeager family", desc: "A relative of the Yeager family line in Marley." },
            { name: "Grice", img: "/characters/grice-family.png", role: "Grice family", desc: "A member of Falco and Colt's extended family in the Liberio internment zone." },
            { name: "Leonhart", img: "/characters/leonhart-family.png", role: "Annie's family", desc: "A relative of Annie's, tied to her family's isolated life and the brutal Warrior training her father imposed on her." },
            { name: "Finger", img: "/characters/finger-family.png", role: "Pieck's family", desc: "A member of Pieck's family within Marley's Eldian district." },
            { name: "Reiner's father", img: "/characters/reiners-father.png", role: "Reiner's estranged father ?", desc: "Reiner's estranged Marleyan father, whose absence shaped his son's turbulent sense of identity." },
            { name: "Comrade D", img: "/characters/comrade-d.png", role: "Titan casualty (Titan)", desc: "An unnamed figure who meets a grim end as one of the mindless Titans roaming the world." },
            { name: "Talking Titan", img: "/characters/talking-titan.png", role: "Anomalous Titan (Titan)", desc: "A rare Titan retaining fragments of speech, a chilling reminder of the humanity trapped within the Titans' monstrous forms." },
            { name: "Greiz", img: "/characters/greiz.png", role: "Volunteer fighter", desc: "A hardened Anti-Marleyan Volunteer loyal to Zeke's cause, killed in the conflict surrounding Eren's plans." },
            { name: "Ogweno", img: "/characters/ogweno.png", role: "Allied volunteer ?", desc: "A volunteer fighter from an allied nation whose fate remains unclear by the story's end." },
            { name: "Nambia", img: "/characters/nambia.png", role: "Allied volunteer ?", desc: "Another Anti-Marleyan Volunteer soldier of uncertain fate." },
        ],
    },
    {
        id: "anti-marleyan",
        name: "Anti-Marleyan Volunteers",
        tagline: "Fighting Marley from within",
        logo: "/logos/eldya.png",
        accent: "border-emerald-800/50 hover:shadow-[0_0_45px_rgba(6,95,70,0.35)]",
        chipColor: "text-emerald-400",
        desc:
            "A resistance force of Eldians and allied nations working to undermine Marley from the shadows, later drawn into Zeke and Eren's competing visions for Eldia's future.",
        characters: [
            { name: "Yelena", img: "/characters/yelena.png", role: "Anti-Marleyan Volunteer, Zeke loyalist", desc: "A fervent believer in Zeke Yeager's plan, a former Marleyan soldier who allies with Eren and the Yeagerists to see her leader's vision through." },
            { name: "Onyankopon", img: "/characters/onyankopon.png", role: "Allied soldier, airship pilot", desc: "An Eldian ally from an allied African nation, notable for piloting Paradis's newly acquired airships in the war's final stretch." },
        ],
    },
    {
        id: "Yeagerists",
        name: "Yeagerists",
        tagline: "Loyal to Eren, to the end",
        logo: "/logos/eldya.png",
        accent: "border-red-700/60 hover:shadow-[0_0_45px_rgba(185,28,28,0.4)]",
        chipColor: "text-red-400",
        desc:
            "A radical faction born from Eren's own supporters within Paradis's military, who seize control of the government in his name and follow him into humanity's final, catastrophic war.",
        characters: [
            { name: "Floch Forster", img: "/characters/floch-forster.png", role: "Yeagerist leader", desc: "A once-minor cadet who becomes a fervent believer in Eren's cause after surviving the war for Paradis. He rises to lead the Yeagerist movement and dies defending Eren's plan in the final battle." },
            { name: "Rico Brzenska", img: "/characters/rico-brzenska.png", role: "Garrison soldier, Yeagerist era", desc: "A capable Garrison soldier who becomes entangled with the Yeagerist movement's rise within Paradis's military." },
            { name: "Hitch Dreyse", img: "/characters/hitch-dreyse.png", role: "MP officer, Yeagerist era", desc: "A sharp-tongued Military Police officer who navigates the chaos of the Yeagerist coup with pragmatic wit." },
            { name: "Samuel Linke-Jackson", img: "/characters/samuel-linke-jackson.png", role: "Yeagerist soldier", desc: "A devoted Yeagerist soldier who dies fighting for Eren's vision of freedom during the final war." },
            { name: "Daz", img: "/characters/daz.png", role: "Yeagerist soldier", desc: "A nervous but loyal soldier swept up in the Yeagerist cause, killed in the fighting that follows." },
            { name: "Oliver", img: "/characters/oliver.png", role: "Yeagerist soldier", desc: "A Yeagerist fighter who falls during the final conflict over Eren's plans." },
            { name: "Wim", img: "/characters/wim.png", role: "Yeagerist soldier", desc: "A soldier drawn into the Yeagerist faction's ranks during the coup." },
            { name: "Holger", img: "/characters/holger.png", role: "Yeagerist soldier", desc: "A Yeagerist follower loyal to Eren's cause." },
            { name: "Surma", img: "/characters/surma.png", role: "Yeagerist soldier", desc: "A member of the Yeagerist movement within the military." },
            { name: "Louise", img: "/characters/louise.png", role: "Yeagerist soldier ?", desc: "A Yeagerist whose ultimate fate is left uncertain." },
        ],
    },
    {
        id: "titans-legends",
        name: "Titans & Legends",
        tagline: "Myths made monstrous",
        logo: "/logos/maria.webp",
        accent: "border-neutral-500/40 hover:shadow-[0_0_45px_rgba(115,115,115,0.3)]",
        chipColor: "text-neutral-300",
        desc:
            "Captured Titans used for research, and the ancient legends whispered about the curse that started it all — figures more myth than man, but no less woven into the story's fabric.",
        characters: [
            { name: "Sawney", img: "/characters/sawney.png", role: "Captured Titan", desc: "One of the first captured Titans, restrained and studied for Hange's early research experiments before ultimately being destroyed." },
            { name: "Beane", img: "/characters/beane.png", role: "Captured Titan", desc: "The second Titan captured alongside Sawney for Hange's research, sharing the same fate." },
            { name: "Helos", img: "/characters/helos.png", role: "Figure of legend", desc: "A figure from ancient Eldian legend, tied to the myths surrounding the Titans' distant origins." },
            { name: "Devil of All Earth", img: "/characters/devil-of-all-earth.png", role: "Mythic figure", desc: "The mythic villain blamed in folklore for cursing Ymir with the power of the Titans — more symbol than fact, but a story every Eldian grows up hearing." },
            { name: "Mirror Man", img: "/characters/mirror-man.png", role: "Figure of an alternate reality ?", desc: "An enigmatic figure glimpsed in a dreamlike, alternate vision of reality, his true nature left deliberately unclear." },
        ],
    },
];

export const CHARACTERS_LANDING = [
    {
        name: "Eren Yeager",
        role: "Attack Titan Shifter",
        img: "/chars/eren.png",
    },
    {
        name: "Mikasa Ackerman",
        role: "Survey Corps",
        img: "/chars/mikasa.png",
    },
    {
        name: "Erwin Smith",
        role: "Survey Corps Commander",
        img: "/chars/erwin.png",
    },
    {
        name: "Levi Ackerman",
        role: "Special Operations Force Head",
        img: "/chars/levi.png",
    },
];