export const OSTS = [
    {
        name: "2Volt",
        artist: "Hiroyuki Sawano",
        time: "06:41",
        url: "/osts/2Volt.mp3",
        bestParts: ["02:12", "04:37"],
        rating: 9.6,
    },
    {
        name: "attack音D",
        artist: "Hiroyuki Sawano",
        time: "04:31",
        url: "/osts/attack音D.mp3",
        bestParts: ["00:50", "01:52", "02:39", "03:45"],
        rating: 9.8,
    },
    {
        name: "Barricades",
        artist: "Hiroyuki Sawano",
        time: "04:20",
        url: "/osts/Barricades.mp3",
        bestParts: ["00:36"],
        rating: 9.1,
    },
    {
        name: "Before Lights Out",
        artist: "Hiroyuki Sawano",
        time: "04:34",
        url: "/osts/Before Lights Out.mp3",
        bestParts: ["01:20"],
        rating: 9.0,
    },
    {
        name: "Building Blocks",
        artist: "Hiroyuki Sawano",
        time: "03:56",
        url: "/osts/Building Blocks.mp3",
        bestParts: ["00:24", "00:56"],
        rating: 9.2,
    },
    {
        name: "Call Your Name",
        artist: "Hiroyuki Sawano",
        time: "04:28",
        url: "/osts/Call Your Name.mp3",
        bestParts: ["00:14", "01:07", "02:28"],
        rating: 9.6,
    },
    {
        name: "Call of Silence",
        artist: "Hiroyuki Sawano",
        time: "02:55",
        url: "/osts/Call of Silence.mp3",
        bestParts: ["00:38", "01:43"],
        rating: 9.6,
    },
    {
        name: "cóunter・attàck-mˈænkάɪnd",
        artist: "Hiroyuki Sawano",
        time: "06:07",
        url: "/osts/cóunter・attàck-mˈænkάɪnd.mp3",
        bestParts: ["00:46", "01:54", "03:25", "04:52"],
        rating: 9.5,
    },
    {
        name: "D.O.A.",
        artist: "Hiroyuki Sawano",
        time: "03:26",
        url: "/osts/D.O.A..mp3",
        bestParts: ["01:23"],
        rating: 9.2,
    },
    {
        name: "E.M.A.",
        artist: "Hiroyuki Sawano",
        time: "05:43",
        url: "/osts/E.M.A..mp3",
        bestParts: ["01:31", "4:39"],
        rating: 9.5,
    },
    {
        name: "ERENthe標 _ Eren The C",
        artist: "Hiroyuki Sawano",
        time: "04:53",
        url: "/osts/ERENthe標 _ Eren The C.mp3",
        bestParts: ["00:35", "03:23"],
        rating: 9.6,
    },
    {
        name: "eye-water",
        artist: "Hiroyuki Sawano",
        time: "03:01",
        url: "/osts/eye-water.mp3",
        bestParts: ["01:46"],
        rating: 9.9,
    },
    {
        name: "Female Titan Extermination",
        artist: "Hiroyuki Sawano",
        time: "05:15",
        url: "/osts/Female Titan Extermination.mp3",
        bestParts: ["01:00", "02:09"],
        rating: 9.6,
    },
    {
        name: "Mika Koboyashi",
        artist: "Hiroyuki Sawano",
        time: "03:51",
        url: "/osts/Mika Koboyashi.mp3",
        bestParts: ["01:01", "02:34", "03:26"],
        rating: 9.7,
    },
    {
        name: "omake-pfadlib",
        artist: "Hiroyuki Sawano",
        time: "03:32",
        url: "/osts/omake-pfadlib.mp3",
        bestParts: ["00:50", "02:05"],
        rating: 9.7,
    },
    {
        name: "Score Eren Awakens",
        artist: "Hiroyuki Sawano",
        time: "03:31",
        url: "/osts/Score Eren Awakens.mp3",
        bestParts: [],
        rating: 9.9,
    },
    {
        name: "son2SeaVer",
        artist: "Hiroyuki Sawano",
        time: "05:21",
        url: "/osts/son2SeaVer.mp3",
        bestParts: ["02:24"],
        rating: 9.0,
    },
    {
        name: "The Reluctant Heroes",
        artist: "Hiroyuki Sawano",
        time: "04:27",
        url: "/osts/The Reluctant Heroes.mp3",
        bestParts: ["00:15", "01:00", "02:00"],
        rating: 9.3,
    },
    {
        name: "TheWeightOfLives",
        artist: "Hiroyuki Sawano",
        time: "05:37",
        url: "/osts/TheWeightOfLives.mp3",
        bestParts: ["01:20", "02:47", "05:13"],
        rating: 9.5,
    },
    {
        name: "Three Dimensional Maneuver",
        artist: "Hiroyuki Sawano",
        time: "05:43",
        url: "/osts/Three Dimensional Maneuver.mp3",
        bestParts: ["00:55", "03:01"],
        rating: 9.6,
    },
    {
        name: "Vogel im Käfig",
        artist: "Hiroyuki Sawano",
        time: "06:20",
        url: "/osts/Vogel im Käfig.mp3",
        bestParts: ["01:43", "03:31", "04:46"],
        rating: 10,
    },
    {
        name: "Wings Of Freedom",
        artist: "Hiroyuki Sawano",
        time: "05:16",
        url: "/osts/Wings Of Freedom.mp3",
        bestParts: ["01:58", "03:10"],
        rating: 9.7,
    },
    {
        name: "XL-TT",
        artist: "Hiroyuki Sawano",
        time: "06:37",
        url: "/osts/XL-TT.mp3",
        bestParts: ["01:13", "02:09", "03:25", "05:20"],
        rating: 9.9,
    },
    {
        name: "YouSeeBIGGIRL/T:T",
        artist: "Hiroyuki Sawano",
        time: "06:03",
        url: "/osts/YouSeeBIGGIRL_TT.mp3",
        bestParts: ["01:27", "04:21"],
        rating: 9.7,
    },
    {
        name: "進撃st-hrn-egt20130629巨人",
        artist: "Hiroyuki Sawano",
        time: "06:17",
        url: "/osts/進撃st-hrn-egt20130629巨人.mp3",
        bestParts: ["00:14", "03:20", "03:38"],
        rating: 9.5,
    },
    {
        name: "進撃vc-pf20130218巨人",
        artist: "Hiroyuki Sawano",
        time: "04:22",
        url: "/osts/進撃vc-pf20130218巨人.mp3",
        bestParts: ["00:18", "00:56", "02:48", "03:26"],
        rating: 9.9,
    },
    {
        name: "T-KT",
        artist: "Hiroyuki Sawano",
        time: "02:55",
        url: "/osts/T-KT.mp3",
        bestParts: ["00:32", "01:39"],
        rating: 9.4,
    },
];

export const OSTS_LANDING = OSTS.sort((a, b) => b.rating - a.rating).slice(0, 3)