let i = 0;

export const SEASON_QUESTIONS = [
    { id: ++i, season: 1, image: "/gallery/bodyparts/2.png" },
    { id: ++i, season: 2, image: "/gallery/bodyparts/3.png" },
    { id: ++i, season: 2, image: "/gallery/bodyparts/4.png" },
    { id: ++i, season: 3, image: "/gallery/bodyparts/5.png" },
    { id: ++i, season: 2, image: "/gallery/bodyparts/7.png" },
    { id: ++i, season: 2, image: "/gallery/bodyparts/8.png" },
    { id: ++i, season: 2, image: "/gallery/bodyparts/9.png" },
    { id: ++i, season: 2, image: "/gallery/bodyparts/10.png" },

    { id: ++i, season: 2, image: "/gallery/eyes/1.png" },
    { id: ++i, season: 1, image: "/gallery/eyes/2.jpg" },
    { id: ++i, season: 10, image: "/gallery/eyes/3.png" },
    { id: ++i, season: 2, image: "/gallery/eyes/4.png" },
    { id: ++i, season: 2, image: "/gallery/eyes/5.png" },
    { id: ++i, season: 3, image: "/gallery/eyes/6.png" },
    { id: ++i, season: 2, image: "/gallery/eyes/7.png" },
    { id: ++i, season: 1, image: "/gallery/eyes/8.png" },
    { id: ++i, season: 1, image: "/gallery/eyes/9.png" },
    { id: ++i, season: 1, image: "/gallery/eyes/10.jpg" },
    { id: ++i, season: 1, image: "/gallery/eyes/11.jpg" },

    { id: ++i, season: 2, image: "/gallery/faces/1.png" },
    { id: ++i, season: 3, image: "/gallery/faces/2.png" },
    { id: ++i, season: 2, image: "/gallery/faces/3.png" },
    { id: ++i, season: 2, image: "/gallery/faces/4.png" },
    { id: ++i, season: 1, image: "/gallery/faces/5.png" },
    { id: ++i, season: 2, image: "/gallery/faces/6.jpg" },
    { id: ++i, season: 1, image: "/gallery/faces/6-1.jpg" },
    { id: ++i, season: 1, image: "/gallery/faces/7.png" },
    { id: ++i, season: 2, image: "/gallery/faces/8.png" },
    { id: ++i, season: 1, image: "/gallery/faces/9.png" },
    { id: ++i, season: 1, image: "/gallery/faces/10.png" },
    { id: ++i, season: 2, image: "/gallery/faces/10-1.png" },
    { id: ++i, season: 2, image: "/gallery/faces/11.png" },
    { id: ++i, season: 2, image: "/gallery/faces/12.png" },
    { id: ++i, season: 3, image: "/gallery/faces/13.png" },
    { id: ++i, season: 3, image: "/gallery/faces/14.png" },
    { id: ++i, season: 2, image: "/gallery/faces/16.png" },
    { id: ++i, season: 2, image: "/gallery/faces/17.png" },
    { id: ++i, season: 2, image: "/gallery/faces/18.png" },
    { id: ++i, season: 1, image: "/gallery/faces/19.png" },
    { id: ++i, season: 2, image: "/gallery/faces/20.png" },
    { id: ++i, season: 2, image: "/gallery/faces/21.png" },
    { id: ++i, season: 1, image: "/gallery/faces/22.png" },
    { id: ++i, season: 2, image: "/gallery/faces/23.webp" },
    { id: ++i, season: 2, image: "/gallery/faces/24.png" },
    { id: ++i, season: 2, image: "/gallery/faces/25.png" },
    { id: ++i, season: 2, image: "/gallery/faces/26.png" },
    { id: ++i, season: 2, image: "/gallery/faces/27.png" },
    { id: ++i, season: 2, image: "/gallery/faces/28.png" },
    { id: ++i, season: 2, image: "/gallery/faces/29.png" },
    { id: ++i, season: 2, image: "/gallery/faces/30.png" },
    { id: ++i, season: 2, image: "/gallery/faces/31.png" },
    { id: ++i, season: 2, image: "/gallery/faces/32.png" },
    { id: ++i, season: 2, image: "/gallery/faces/33.png" },
    { id: ++i, season: 3, image: "/gallery/faces/34.png" },

    { id: ++i, season: 2, image: "/gallery/titans/1.png" },
    { id: ++i, season: 3, image: "/gallery/titans/2.png" },
    { id: ++i, season: 1, image: "/gallery/titans/3.png" },
    { id: ++i, season: 2, image: "/gallery/titans/4.png" },
    { id: ++i, season: 2, image: "/gallery/titans/5.png" },
    { id: ++i, season: 3, image: "/gallery/titans/6.png" },
    { id: ++i, season: 1, image: "/gallery/titans/7.png" },
    { id: ++i, season: 1, image: "/gallery/titans/8.png" },
    { id: ++i, season: 3, image: "/gallery/titans/9.png" },
    { id: ++i, season: 1, image: "/gallery/titans/10.png" },
    { id: ++i, season: 2, image: "/gallery/titans/11.png" },
    { id: ++i, season: 3, image: "/gallery/titans/12.png" },
    { id: ++i, season: 3, image: "/gallery/titans/13.png" },
    { id: ++i, season: 3, image: "/gallery/titans/14.png" },
    { id: ++i, season: 2, image: "/gallery/titans/15.png" },
    { id: ++i, season: 2, image: "/gallery/titans/16.png" },
    { id: ++i, season: 2, image: "/gallery/titans/17.png" },
    { id: ++i, season: 2, image: "/gallery/titans/18.png" },

    { id: ++i, season: 1, image: "/gallery/visuals/1.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/2.png" },
    { id: ++i, season: 2, image: "/gallery/visuals/3.png" },
    { id: ++i, season: 2, image: "/gallery/visuals/4.png" },
    { id: ++i, season: 2, image: "/gallery/visuals/5.png" },
    { id: ++i, season: 2, image: "/gallery/visuals/6.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/7.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/8.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/9.png" },
    { id: ++i, season: 2, image: "/gallery/visuals/10.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/12.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/13.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/15.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/16.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/17.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/18.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/19.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/20.png" },
    { id: ++i, season: 3, image: "/gallery/visuals/21.png" },
];

export const QUESTION_COUNT = 10;
export const ANSWER_TIME_MS = 8000;
export const REVEAL_TIME_MS = 3000;
export const SEASON_CHOICES = [1, 2, 3, 4];