export const SONGS = [
    {
        id: "s1-op1",
        type: "opening",
        index: 1,
        season: "Season 1",
        title: "Guren no Yumiya",
        artist: "Linked Horizon",
        episodes: "Episodes 1-13",
        youtubeId: "M7jom3DhDfo",
        cover: "/songs/S1-OP1.jpg",
    },
    {
        id: "s1-ed1",
        type: "ending",
        index: 1,
        season: "Season 1",
        title: "Utsukushiki Zankoku na Sekai",
        artist: "Yoko Hikasa",
        episodes: "Episodes 1-24",
        youtubeId: "gJIMkSn_U5o",
        cover: "/songs/S1-ED1.jpg",
    },
    {
        id: "s1-op2",
        type: "opening",
        index: 2,
        season: "Season 1",
        title: "Jiyuu no Tsubasa",
        artist: "Linked Horizon",
        episodes: "Episodes 14-25",
        youtubeId: "XN2cV23_nZ0",
        cover: "/songs/S1-OP2.jpg",
    },
    {
        id: "s1-ed2",
        type: "ending",
        index: 2,
        season: "Season 1",
        title: "Great Escape",
        artist: "Cinema Staff",
        episodes: "Episode 25",
        youtubeId: "_ysUmg7Q1YE",
        cover: "/songs/S1-ED2.jpg",
    },
    {
        id: "s2-op1",
        type: "opening",
        index: 1,
        season: "Season 2",
        title: "Shinzou wo Sasageyo",
        artist: "Linked Horizon",
        episodes: "Episodes 26-37",
        youtubeId: "KSD2s_IErxg",
        cover: "/songs/S2-OP1.jpg",
    },
    {
        id: "s2-ed1",
        type: "ending",
        index: 1,
        season: "Season 2",
        title: "Yuugure no Tori (Bird at Dusk)",
        artist: "Shinsei Kamattechan",
        episodes: "Episodes 26-37",
        youtubeId: "rbfHY8mkhT8",
        cover: "/songs/S2-ED1.jpg",
    },
    {
        id: "s3-op1",
        type: "opening",
        index: 1,
        season: "Season 3 Part 1",
        title: "Red Swan",
        artist: "Yoshiki feat. Hyde",
        episodes: "Episodes 38-49",
        youtubeId: "OC_olaqjv8Y",
        cover: "/songs/S3-OP1.jpg",
    },
    {
        id: "s3-ed1",
        type: "ending",
        index: 1,
        season: "Season 3 Part 1",
        title: "Akatsuki no Requiem",
        artist: "Linked Horizon",
        episodes: "Episodes 38-49",
        youtubeId: "cGBk7edLp_E",
        cover: "/songs/S3-ED1.jpg",
    },
    {
        id: "s3-op2",
        type: "opening",
        index: 2,
        season: "Season 3 Part 2",
        title: "Shoukei to Shikabane no Michi",
        artist: "Linked Horizon",
        episodes: "Episodes 50-59",
        youtubeId: "jhYg5NrN-r8",
        cover: "/songs/S3-OP2.jpg",
    },
    {
        id: "s3-ed2",
        type: "ending",
        index: 2,
        season: "Season 3 Part 2",
        title: "Name of Love",
        artist: "Cinema Staff",
        episodes: "Episodes 50-59",
        youtubeId: "9X0JVOQKt-c",
        cover: "/songs/S3-ED2.jpg",
    },
    {
        id: "s4-op1",
        type: "opening",
        index: 1,
        season: "Season 4 Part 1",
        title: "My War",
        artist: "Shinsei Kamattechan",
        episodes: "Episodes 60-75",
        youtubeId: "pASAxC_ToB8",
        cover: "/songs/S4-OP1.jpg",
    },
    {
        id: "s4-ed1",
        type: "ending",
        index: 1,
        season: "Season 4 Part 1",
        title: "Shock",
        artist: "Yuko Ando",
        episodes: "Episodes 60-75",
        youtubeId: "ehsvwe58Zls",
        cover: "/songs/S4-ED1.jpg",
    },
    {
        id: "s4-op2",
        type: "opening",
        index: 1,
        season: "Season 4 Part 2",
        title: "The Rumbling",
        artist: "SiM",
        episodes: "Episodes 76-87",
        youtubeId: "hWHefLUCV2o",
        cover: "/songs/S4-OP2.jpg",
    },
    {
        id: "s4-ed2",
        type: "ending",
        index: 1,
        season: "Season 4 Part 2",
        title: "Akuma no Ko",
        artist: "Ai Higuchi",
        episodes: "Episodes 76-89",
        youtubeId: "9lnh--ZOPyo",
        cover: "/songs/S4-ED2.jpg",
    },
];